### ISSUE TITLE
seq_ent = torch.cat([torch.index_select(seq_out[i,:,:],0,ids[i,:].long()).unsqueeze(0) for i in range(batch_size)], 0) # [batchsize, 4, 768]

### ISSUE THREAD

**Issue by Dimas263** [taishan1994/pytorch_bert_relation_extraction#6]
Hello sir, what should i change if I only have 4 labels in _rel_dict.json_?

```json
{
  "unknown": 0,
  "夫妻": 1,
  "父母": 2,
  "兄弟姐妹": 3,
  "上下级": 4,
}
```

I have a problem when I run models.py

run with CPU
```
seq_ent = torch.cat([torch.index_select(seq_out[i,:,:],0,ids[i,:].long()).unsqueeze(0) for i in range(batch_size)], 0) # [batchsize, 4, 768]

IndexError: index out of range in self
```

run with GPU
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-43fe30517134> in <module>()
     98       # print(train_data['ids'].shape)
     99 
--> 100       token_ids = train_data['token_ids'].to(device)
    101       attention_masks = train_data['attention_masks'].to(device)
    102       token_type_ids = train_data['token_type_ids'].to(device)

RuntimeError: CUDA error: device-side assert triggered
```

**Comment by taishan1994** [comment]
> Hello sir, what should i change if I only have 4 labels in _rel_dict.json_?
> 
> ```json
> {
>   "unknown": 0,
>   "夫妻": 1,
>   "父母": 2,
>   "兄弟姐妹": 3,
>   "上下级": 4,
> }
> ```
> 
> I have a problem when I run models.py
> 
> run with CPU
> 
> ```
> seq_ent = torch.cat([torch.index_select(seq_out[i,:,:],0,ids[i,:].long()).unsqueeze(0) for i in range(batch_size)], 0) # [batchsize, 4, 768]
> 
> IndexError: index out of range in self
> ```
> 
> run with GPU
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-14-43fe30517134> in <module>()
>      98       # print(train_data['ids'].shape)
>      99 
> --> 100       token_ids = train_data['token_ids'].to(device)
>     101       attention_masks = train_data['attention_masks'].to(device)
>     102       token_type_ids = train_data['token_type_ids'].to(device)
> 
> RuntimeError: CUDA error: device-side assert triggered
> ```
> 
> **if you don't mind can you correct my code [here](https://github.com/Dimas263/Research_NLP_Biomedical_Relation_Extraction_Bert)**

When you create a dataset, you need to map the tags to between 0-4

**Comment by Dimas263** [comment]
Thank you, I solved my problem
